version: '3'
services:
  job-scheduler:
    container_name: job-scheduler
    build:
      context: .
      dockerfile: Dockerfile-JobScheduler
    depends_on:
    - redis
    ports:
    - "8080:8080"
    links:
    - redis
    networks:
    - job-scheduler-network
  job-scheduler-agent:
    container_name: job-scheduler-agent
    build:
      context: .
      dockerfile: Dockerfile-Agent
    depends_on:
    - redis
    links:
    - redis
    networks:
    - job-scheduler-network
  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
    networks:
    - job-scheduler-network
    
networks:
  job-scheduler-network: